name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Fuseki
      run: ./gradlew startfuseki
    - name: Build
      run: ./gradlew build
    - name: Query
      run: ./gradlew owlQuery
    - name: Upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/
    - name: Generate Docs
      run: ./gradlew generateDocs